### ISSUE TITLE
Building IncludeOS on Ubuntu 17.10

### ISSUE THREAD

**Issue by oleaamot** [includeos/includeos.org#3]
IncludeOS builds on Ubuntu 17.10 after applying the following patches and running "cd build_x86_64/ && make":

* Remove references to __float128 in /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h
https://people.gnome.org/~ole/includeos/ubuntu-17.10-c++-20171029.patch

* Configure "set(libliveupdate OFF)" and "option(libliveupdate "Build and install LiveUpdate" OFF)" in CMakeLists.txt
https://people.gnome.org/~ole/includeos/includeos-libliveupdate-off-20171029.patch

Enjoy,
Ole

**Comment by perbu** [comment]
Hi Ole.

This is the repo for the website includeos.org.  Here is the official IncludeOS issue tracker: https://github.com/hioa-cs/IncludeOS/issues

I've posted the bug there and mentioned you. I'll close this and track the issue there.

https://github.com/hioa-cs/IncludeOS/issues/1549

Thanks!
